services:
  - type: web
    name: umrzoq-portfolio
    runtime: python
    buildCommand: echo "No build needed"
    startCommand: python3 app.py
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
